<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\City;
use App\Models\Barangay;

class BarangaySeeder extends Seeder
{
    public function run()
    {
        $barangays = [
            // DAVAO DEL NORTE
            'Island Garden City of Samal' => [
                'Adecor',
                'Anonang',
                'Aumbay',
                'Balet',
                'Bandera',
                'Blessed Village',
                'Caliclic',
                'Camudmud',
                'Cogon',
                'Cogon (Babak District)',
                'Dadatan',
                'Del Monte',
                'Guilon',
                'Kinawitnon',
                'Libuak',
                'Libertad',
                'Licup',
                'Limao',
                'Linosutan',
                'Mambago-A',
                'Mambago-B',
                'Miranda',
                'Moncado',
                'Peñaplata',
                'Poblacion (Babak District)',
                'Poblacion (Kaputian District)',
                'San Agustin',
                'San Antonio',
                'San Isidro (Babak District)',
                'San Isidro (Kaputian District)',
                'San Jose',
                'San Miguel',
                'San Remigio',
                'Santa Cruz',
                'Santo Niño',
                'Sion',
                'Tagbaobo',
                'Tagbay',
                'Tagdaliao',
                'Tagpopongan',
                'Tambo',
                'Toril',
                'Zaragoza',
            ],

            'Panabo City' => [
                'A. O. Floirendo',
                'Datu Abdul Dadia',
                'Buenavista',
                'Cacao',
                'Cagangohan',
                'Consolacion',
                'Dapco',
                'Gredu (Poblacion)',
                'J.P. Laurel',
                'Kasilak',
                'Katipunan',
                'Katualan',
                'Kauswagan',
                'Kiotoy',
                'Little Panay',
                'Lower Panaga (Roxas)',
                'Mabunao',
                'Maduao',
                'Malativas',
                'Manay',
                'Nanyo',
                'New Malaga (Dalisay)',
                'New Malitbog',
                'New Pandan (Poblacion)',
                'New Visayas',
                'Quezon',
                'Salvacion',
                'San Francisco (Poblacion)',
                'San Nicolas',
                'San Pedro',
                'San Roque',
                'San Vicente',
                'Santa Cruz',
                'Santo Niño (Poblacion)',
                'Sindaton',
                'Southern Davao',
                'Tagpore',
                'Tibungol',
                'Upper Licanan',
                'Waterfall',
            ],

            'Tagum City' => [
                'Apokon',
                'Bincungan',
                'Busaon',
                'Canocotan',
                'Cuambogan',
                'La Filipina',
                'Liboganon',
                'Madaum',
                'Magdum',
                'Mankilam',
                'New Balamban',
                'Nueva Fuerza',
                'Pagsabangan',
                'Pandapan',
                'San Agustin',
                'San Isidro',
                'San Miguel',
                'Visayan Village',
                'Magugpo Poblacion',
                'Magugpo East',
                'Magugpo North',
                'Magugpo South',
                'Magugpo West',
            ],

            'Asuncion' => [
                'Bakat',
                'Binancian',
                'Buenasuerte',
                'Cabidianan',
                'Camansa',
                'Cambanogoy',
                'Camoning',
                'Canatan',
                'Concepcion',
                'Bukal',
                'Magatos',
                'Napungas',
                'New Bantayan',
                'Pamacaun',
                'Poblacion',
                'San Vicente',
                'Sonlon',
            ],

            'Braulio E. Dujali' => [
                'Cabaywa',
                'Dujali',
                'Magupising',
                'New Casay',
                'Tanglaw',
            ],

            'Carmen' => [
                'Alejal',
                'Anibongan',
                'Asuncion',
                'Cebulano',
                'Guadalupe',
                'Ising',
                'La Paz',
                'Mabaus',
                'Mabuhay',
                'Magsaysay',
                'Mangalcal',
                'Minda',
                'New Camiling',
                'Salvacion',
                'San Isidro',
                'Santo Niño',
                'Taba',
                'Tibulao',
                'Tubod',
                'Tuganay',
            ],

            'Kapalong' => [
                'Adequan',
                'Balusbos',
                'Katipunan',
                'Luna',
                'Mabantao',
                'Mamacao',
                'Maniki',
                'Pag-asa',
                'Paiton',
                'Poblacion',
                'Semong',
                'Sua-on',
                'Tampa',
                'Tiburcia',
            ],

            'New Corella' => [
                'Cabidianan',
                'Del Pilar',
                'El Salvador',
                'Erusan',
                'Limba-an',
                'Mambing',
                'Mesaoy',
                'New Bohol',
                'New Cortez',
                'Patrocenio',
                'Poblacion',
                'Queensrow',
                'San Roque',
                'Santa Cruz',
                'Santa Fe',
                'Santo Niño',
                'Suawon',
            ],

            'San Isidro' => [
                'Dacudao',
                'Datu Balong',
                'Kipalili',
                'Linao',
                'Liñayon',
                'Monte Dujali',
                'Poblacion',
                'Sabangan',
                'San Miguel',
                'Santo Niño',
                'Sawata',
            ],

            'Santo Tomas' => [
                'Balagunan',
                'Bobongon',
                'Casig-Ang',
                'Esperanza',
                'Kimamon',
                'Kinamayan',
                'La Libertad',
                'Lungag',
                'New Katipunan',
                'New Visayas',
                'Pantaron',
                'Poblacion',
                'Salvacion',
                'San Agustin',
                'San Jose',
                'San Miguel',
                'San Vicente',
                'Talomo',
                'Tibal-og',
                'Tulalian',
            ],

            'Talaingod' => [
                'Dagohoy',
                'Palma Gil',
                'Sto. Niño',
            ],

            // DAVAO DEL SUR
            'Digos City' => [
                'Aplaya',
                'Balabag',
                'Binaton',
                'Colorado',
                'Cogon',
                'Dawis',
                'Dulangan',
                'Goma',
                'Igpit',
                'Kiagot',
                'Lungag',
                'Matti',
                'Ruparan',
                'San Agustin',
                'San Jose (Poblacion)',
                'San Roque',
                'Sinawilan',
                'Soong',
                'Tiguman',
                'Tres de Mayo',
                'Zone I (Poblacion)',
                'Zone II (Poblacion)',
                'Zone III (Poblacion)',
            ],

            'Bansalan' => [
                'Alegre',
                'Alta Vista',
                'Anonang',
                'Bitaug',
                'Bonifacio',
                'Buenavista',
                'Darapuay',
                'Dolo',
                'Eman',
                'Poblacion',
                'Kinuskusan',
                'Libertad',
                'Linawan',
                'Mabuhay',
                'Mabunga',
                'Managa',
                'Marber',
                'New Clarin',
                'Poblacion Dos',
                'Rizal',
                'Sibayan',
                'Tinongtongan',
                'Tubod',
                'Union',
            ],

            'Hagonoy' => [
                'Aplaya',
                'Balutakay',
                'Clib',
                'Guihing',
                'Hagonoy Crossing',
                'Hilan',
                'Ilangay',
                'Kibuaya',
                'La Union',
                'Lanuro',
                'Lapulabao',
                'Leling',
                'Lower Bala',
                'Mahayahay',
                'Malabang',
                'Maliit Digos',
                'New Quezon',
                'Paligue',
                'Poblacion',
                'Sacub',
                'San Guillermo',
                'San Isidro',
                'Sinayawan',
                'Upper Bala',
            ],

            'Kiblawan' => [
                'Bagumbayan',
                'Balasiao',
                'Bonifacio',
                'Cogon-Bacaca',
                'Dapok',
                'Ihan',
                'Kimlawis',
                'Little Baguio',
                'Mabuhay',
                'Maraga-a',
                'Nasodsod',
                'New Sibonga',
                'Panaglib',
                'Poblacion',
                'Tacub',
            ],

            'Magsaysay' => [
                'Barayong',
                'Buhay',
                'Colongulo',
                'Dalurong',
                'Doña Josefina',
                'Imelda',
                'Kanapulo',
                'Kasuga',
                'Lower Bala',
                'Mabini',
                'Malawanit',
                'New Ilocos',
                'Poblacion',
                'San Isidro',
                'Sinaragan',
                'Upper Bala',
            ],

            'Malalag' => [
                'Bagumbayan',
                'Baybay',
                'Bolton',
                'Buas',
                'Bulacan',
                'Caputian',
                'Tagansule',
                'Poblacion',
                'Kiblat',
                'Mabini',
                'New Baclayon',
                'Pitu',
                'San Isidro',
            ],

            'Matanao' => [
                'Asbang',
                'Asinan',
                'Bagumbayan',
                'Balnate',
                'Bangkal',
                'Buas',
                'Cabligan',
                'Camanchiles',
                'Canidkid',
                'Carmencita',
                'Colonsabak',
                'Cultura',
                'Dongan-Pekong',
                'Kabasagan',
                'Kapok',
                'Kauswagan',
                'Kibao',
                'La Suerte',
                'Lower Marber',
                'Lzoon',
                'Mabini',
                'Manga',
                'Matilo',
                'New Katipunan',
                'New Murcia',
                'Poblacion',
                'Saboy',
                'San Jose',
                'San Miguel',
                'San Vicente',
                'Saub',
                'Savannah',
                'Sinaragan',
                'Sinaragan East',
                'Sinawilan',
                'Talahik',
                'Tibongbong',
                'Ticulon',
            ],

            'Padada' => [
                'Almendras',
                'Don Sergio Osmeña Sr.',
                'Lower Katipunan',
                'Piape',
                'Pob. (Roxas)',
                'Pob. (Quezon)',
                'Pob. (Rizal)',
                'Pob. (Macarthur)',
                'Lower Limonzo',
                'New Baclayon',
                'Northern Paligue',
                'Southern Paligue',
                'San Isidro',
                'Tulogan',
                'Upper Limonzo',
            ],

            'Santa Cruz' => [
                'Astorga',
                'Bato',
                'Coronon',
                'Darong',
                'Dololon',
                'Inawayan',
                'Jose Rizal',
                'Matutungan',
                'Nabangig',
                'Poblacion',
                'Sibulan',
                'Tagabuli',
                'Tibolo',
                'Tuban',
                'Jose Abad Santos (Recovo)',
            ],

            'Sulop' => [
                'Balasinon',
                'Bato',
                'Buguis',
                'Carre',
                'Casalngan',
                'Harada Butai',
                'Katipunan',
                'Kiblagon',
                'Labon',
                'Laperas',
                'Litos',
                'Luparan',
                'Mckinley',
                'New Cebu',
                'Osmeña',
                'Parame',
                'Poblacion',
                'Solongvale',
                'Tagolilong',
                'Tala-o',
                'Talas',
                'Tamban',
                'Tanwalang',
                'Tañgub',
                'Waterfall',
            ],

            // DAVAO DE ORO (COMPOSTELA VALLEY)
            'Compostela' => [
                'Bagongon',
                'Gabi',
                'Lagab',
                'Mangayon',
                'Mapaca',
                'Maparat',
                'New Alegria',
                'Ngan',
                'Osmeña',
                'Panansalan',
                'Poblacion',
                'San Jose',
                'San Miguel',
                'Tamia',
            ],

            'Laak' => [
                'Aguinaldo',
                'Ampawid',
                'Banbanon',
                'Banlag',
                'Binasbas',
                'Datu Ampunan',
                'Kaligutan',
                'Kidawa',
                'Kilagding',
                'Laak',
                'Langgawisan',
                'Maligwak',
                'Manurigao',
                'Poblacion',
            ],

            'Mabini' => [
                'Andili',
                'Cadunan',
                'Del Pilar',
                'Golden Valley (Maraut)',
                'Libodon',
                'Mabini',
                'Pangibiran',
                'Pindasan',
                'San Antonio',
                'San Jose',
                'Teresa',
            ],

            'Maco' => [
                'Anibongan',
                'Anislagan',
                'Binuangan',
                'Bucana',
                'Calabcab',
                'Concepcion',
                'Dumlan',
                'Elizalde (Somil)',
                'Gubatan',
                'Kinuban',
                'Langgam',
                'Lapu-lapu',
                'Limbo',
                'Lumatab',
                'Magading',
                'Maco',
                'Mainit',
                'Mapaang',
                'Masara',
                'New Asturias',
                'New Barili',
                'New Leyte',
                'New Visayas',
                'Panangan',
                'Panibasan',
                'San Juan',
                'San Roque',
                'Sangab',
                'Santo Niño',
                'Tagbaros',
                'Teresa',
            ],

            'Maragusan' => [
                'Bagong Silang',
                'Bahi',
                'Cambagang',
                'Coronobe',
                'Lahi',
                'Langgawisan',
                'Mabugnao',
                'Magcagong',
                'Mahayahay',
                'Mapawa',
                'Maragusan',
                'New Albay',
                'New Katipunan',
                'New Man-ay',
                'Nueva Estrella',
                'Paloc',
                'Pamintaran',
                'Parasanon',
                'Talian',
                'Tandik',
                'Tigbao',
                'Tupaz',
            ],

            'Mawab' => [
                'Andap',
                'Bawani',
                'Concepcion',
                'Malinawon',
                'Nueva Visayas',
                'Nueva Villa',
                'Poblacion',
                'Salvacion',
                'Saosao',
                'Sawangan',
                'Tuboran',
            ],

            'Monkayo' => [
                'Awao',
                'Babag',
                'Banlag',
                'Baylo',
                'Casoon',
                'Haguimitan',
                'Inambatan',
                'Macopa',
                'Mamunga',
                'Naboc',
                'Olaycon',
                'Pasian (Habay)',
                'Poblacion',
                'Rizal',
                'Salvacion',
                'San Isidro',
                'San Jose',
                'Tagdangua',
                'Tubo-tubo (New Del Monte)',
                'Union',
                'Upper Ulip',
            ],

            'Nabunturan' => [
                'Anislagan',
                'Antequera',
                'Basak',
                'Bayabas',
                'Bukal',
                'Cabacungan',
                'Cabidianan',
                'Dumagooc',
                'Katipunan',
                'Libasan',
                'Linda',
                'Magading',
                'Magsaysay',
                'Mainit',
                'Manat',
                'Matilo',
                'New Dauis',
                'Ogao',
                'Pangutosan',
                'Poblacion',
                'San Isidro',
                'San Roque',
                'San Vicente',
                'Santo Niño',
                'Sasa',
            ],

            'New Bataan' => [
                'Andap',
                'Bantacan',
                'Batinao',
                'Cabinuangan',
                'Camanlangan',
                'Cogonon',
                'Fatima',
                'Kahayag',
                'Katipunan',
                'Magsaysay',
                'Manurigao',
                'New Barili',
                'New Visayas',
                'Pagsabangan',
                'Panag',
                'Panoraon',
                'Poblacion',
                'San Roque',
            ],

            'Pantukan' => [
                'Araibo',
                'Bongabong',
                'Bongbong',
                'Kingking',
                'Magnaga',
                'Matiao',
                'Napnapan',
                'P. Fuentes',
                'Pantukan',
                'Tagugpo',
                'Tambongon',
                'Tibagon',
            ],

            'Montevista' => [
                'Banagbanag',
                'Bantuanon',
                'Camansi',
                'Canidkid',
                'Dauman',
                'Inambatan',
                'Lebanon',
                'Linoan',
                'Mayaon',
                'New Calape',
                'New Visayas',
                'Patrocenio',
                'Poblacion',
                'San Jose',
                'Prosperidad',
            ],

            // DAVAO OCCIDENTAL
            'Don Marcelino' => [
                'Calian',
                'Chinaboy',
                'Dalupan',
                'Don Aurelio Chicote',
                'Kalbay',
                'Kibalatong',
                'Kinanga',
                'Lais',
                'Lapuan',
                'Linadasan',
                'Mabuhay',
                'Macol',
                'Manaol',
                'Managa',
                'Nueva Villa',
                'Poblacion',
                'Senatorial',
                'Talaguton',
                'West Paligue',
            ],

            'Jose Abad Santos' => [
                'Butuan',
                'Buguis',
                'Camalian',
                'Carahayan',
                'Culaman',
                'Gaudencio Antonio',
                'Lavigan',
                'Maan',
                'Magangit',
                'Nuing',
                'Poblacion (Culaman)',
                'Tanuman',
            ],

            'Malita' => [
                'Bito',
                'Bolila',
                'Buhangin',
                'Culaman',
                'Datu Danwata',
                'Demoloc',
                'Felis',
                'Fishing Village',
                'Florencia',
                'Gardenia',
                'Kibalatong',
                'Kidalapong',
                'Kinangan',
                'Lacaron',
                'Lagumit',
                'Lakamanok',
                'Lacaron',
                'Little Baguio',
                'Ligos',
                'Macol',
                'Mana',
                'New Agutayan',
                'New Argao',
                'New Clarin',
                'Pangaleon',
                'Pinalpalan',
                'Poblacion',
                'Sangay',
                'Tical',
                'Tibongbong',
            ],

            'Santa Maria' => [
                'Asbang',
                'Basiawan',
                'Buca',
                'Cadaatan',
                'Cablalan',
                'Kidadan',
                'Kisulad',
                'Linadasan',
                'New Cebu',
                'New Lagao',
                'New Lawa-an',
                'Poblacion',
                'Pongpong',
                'Tanglad',
                'Tibongbong',
                'Zion',
            ],

            'Sarangani' => [
                'Batuganding',
                'Camahual',
                'Camalig',
                'Gomtago',
                'Lamin',
                'Lipol',
                'Mabila',
                'Patulang',
                'Poblacion',
                'Tinina',
                'Tucal',
            ],

            // DAVAO ORIENTAL
            'Mati City' => [
                'Badas',
                'Bobon',
                'Buso',
                'Cabuaya',
                'Culian',
                'Dahican',
                'Danao',
                'Dawan',
                'Don Enrique Lopez',
                'Don Martin Marundan',
                'Don Salvador Lopez, Sr.',
                'Langka',
                'Lawigan',
                'Libudon',
                'Luban',
                'Macambol',
                'Mamali',
                'Matiao',
                'Mayo',
                'Sainz',
                'Sanghay',
                'Tagabakid',
                'Tagbinonga',
                'Taguibo',
                'Tamisan',
                'Central (Pob.)',
                'Codo (Pob.)',
                'Sainz (Pob.)',
            ],

            'Baganga' => [
                'Baculin',
                'Batiano',
                'Binondo',
                'Campawan',
                'Batawan',
                'Central (Pob.)',
                'Dapnan',
                'Kinablangan',
                'Lambajon',
                'Lucod',
                'Mahan-ub',
                'Salingcomot',
                'San Isidro',
                'San Victor',
            ],

            'Banaybanay' => [
                'Cabangcalan',
                'Caganganan',
                'Calubihan',
                'Cawayanan',
                'Causwagan',
                'Mogbongcogon',
                'Pintatagan',
                'Poblacion',
                'Piso Proper',
                'Rang-ay',
                'San Vicente',
            ],

            'Boston' => [
                'Caatihan',
                'Cabasagan',
                'Poblacion',
                'Sibajay',
                'Simulao',
            ],

            'Caraga' => [
                'Baon',
                'Davao del Norte Boundary',
                'Del Pilar',
                'Josefina',
                'Lamiawan',
                'Manorigao',
                'Pichon',
                'Poblacion',
                'Sobrecarey',
                'Teresa',
            ],

            'Cateel' => [
                'Aliwagwag',
                'Arampudji',
                'Astorga',
                'Bagbayon',
                'Baybay',
                'Poblacion',
                'Bitaogan',
                'Bobon',
                'Cabuaya',
                'Cagmang',
                'Cagdianao',
                'Central (Pob.)',
                'Gamuton',
                'Hagonghong',
                'Herminia',
                'Javier',
                'Lavigan',
                'Lュ-og',
                'Mainit',
                'Malinao',
                'Malido',
                'Marayag',
                'Minsalay',
                'Pichon',
                'Taytayan',
            ],

            'Governor Generoso' => [
                'Anitap',
                'Bagumbayan',
                'Crispin Dela Cruz',
                'Lavigan',
                'Luban',
                'Magdug',
                'Matiao',
                'Montserrat',
                'Nangan',
                'Poblacion',
                'Pundaguitan',
                'San Isidro',
                'San Jose',
                'Surop',
                'Tagabobe',
                'Taglibas',
                'Tagugpo',
                'Tandang Sora',
                'Tibanban',
                'Tiblawan',
                'Tinaytayan',
                'Upper Tibanban',
            ],

            'Lupon' => [
                'Bagumbayan',
                'Calapagan',
                'Cocornon',
                'Corporacion',
                'Galib',
                'Ilangay',
                'Langka',
                'Lantawan',
                'Libay-libay',
                'Macangao',
                'Magsaysay',
                'Mahayahay',
                'Maragatas',
                'Nueva Esperanza',
                'Poblacion',
                'San Ignacio',
                'San Isidro',
                'San Jose',
                'Tagboa',
                'Tagugpo',
            ],

            'Manay' => [
                'Adlay',
                'Badas',
                'Caatihan',
                'Cayawan',
                'Central (Pob.)',
                'Lambog',
                'Libay',
                'Madrid',
                'Mambing',
                'Old Macopa',
                'Pandasan',
                'Salingcomot',
                'San Ignacio',
                'Santo Rosario',
                'Tagbinonga',
                'Taytayan',
            ],

            'San Isidro' => [
                'Bitaogan',
                'Bobonao',
                'Bobon',
                'Bongabong',
                'Cambagang',
                'Camarines',
                'Cambaleon',
                'Dapnan',
                'Golden Valley (Maraut)',
                'Poblacion',
                'San Roque',
            ],

            'Tarragona' => [
                'Ayala',
                'Cabagayan',
                'Central (Pob.)',
                'Dadong',
                'Jovellar',
                'Licawayan',
                'Limot',
                'Lucatan',
                'Magdug',
                'Ompao',
                'Talisay',
                'Tomoaong',
            ],

            // DAVAO CITY
            'Davao City' => [
                // Poblacion District
                '1-A (Pob.)',
                '2-A (Pob.)',
                '3-A (Pob.)',
                '4-A (Pob.)',
                '5-A (Pob.)',
                '6-A (Pob.)',
                '7-A (Pob.)',
                '8-A (Pob.)',
                '9-A (Pob.)',
                '10-A (Pob.)',
                '11-B (Pob.)',
                '12-B (Pob.)',
                '13-B (Pob.)',
                '14-B (Pob.)',
                '15-B (Pob.)',
                '16-B (Pob.)',
                '17-B (Pob.)',
                '18-B (Pob.)',
                '19-B (Pob.)',
                '20-B (Pob.)',
                '21-C (Pob.)',
                '22-C (Pob.)',
                '23-C (Pob.)',
                '24-C (Pob.)',
                '25-C (Pob.)',
                '26-C (Pob.)',
                '27-C (Pob.)',
                '28-C (Pob.)',
                '29-C (Pob.)',
                '30-C (Pob.)',
                '31-D (Pob.)',
                '32-D (Pob.)',
                '33-D (Pob.)',
                '34-D (Pob.)',
                '35-D (Pob.)',
                '36-D (Pob.)',
                '37-D (Pob.)',
                '38-D (Pob.)',
                '39-D (Pob.)',
                '40-D (Pob.)',

                // Agdao District
                'Agdao',
                'Angalan',
                'Bago Aplaya',
                'Bago Gallera',
                'Bago Oshiro',
                'Baguio',
                'Binugao',
                'Bucana',
                'Bunawan',
                'Communal',
                'Gumalang',
                'Gumtan',
                'Lasang',
                'Magsaysay',
                'Mandug',
                'Panacan',
                'Paquibato',
                'Sasa',
                'Tibungco',
                'Tigatto',
                'Waan',
                'Wilfredo Aquino',

                // Baguio District
                'Alejandra Navarro (Lasang)',
                'Baguio',
                'Cabantian',
                'Dacudao',
                'Ilang',
                'Indangan',
                'Lizada',
                'Lubogan',
                'Magtuod',
                'Matina Aplaya',
                'Matina Crossing',
                'Matina Pangi',
                'Tacunan',
                'Tagakpan',
                'Tawan-tawan',
                'Vicente Hizon Sr.',

                // Buhangin District
                'Buhangin Proper',
                'Bunawan Proper',
                'Indangan',
                'Mandug',
                'Tigatto',
                'Cabantian',
                'Leon Garcia Sr.',

                // Calinan District
                'Alambre',
                'Baguio',
                'Balutakay',
                'Bangkas Heights',
                'Biao Escuela',
                'Biao Guianga',
                'Biao Joaquin',
                'Caima',
                'Calinan Poblacion',
                'Carmen',
                'Dacudao',
                'Daliao',
                'Daliaon Plantation',
                'Dominga',
                'Gumalang',
                'Gumitan',
                'Lacson',
                'Lamanan',
                'Langan',
                'Malagos',
                'Mapula',
                'Mariana',
                'Marilog Proper',
                'Salig',
                'Santo Niño',
                'Sibulan',
                'Subasta',
                'Suawan',
                'Tacunan',
                'Tamugan',
                'Tamayong',
                'Tibuloy',
                'Tugbok',
                'Wangan',

                // Marilog District
                'Baganihan',
                'Baguio',
                'Datu Salumay',
                'Gumitan',
                'Malabog',
                'Malagos',
                'Marilog Proper',
                'Santo Niño',
                'Suawan',
                'Tamugan',
                'Tigatto',

                // Paquibato District
                'Astorga',
                'Colosas',
                'Datu Salumay',
                'Gumitan',
                'Kauswagan',
                'Magwawa',
                'Paquibato Proper',
                'Rafael Castillo',
                'Riverside',
                'Tacunan',
                'Talagutong',
                'Tawan-tawan',

                // Talomo District
                'Acacia',
                'Baganihan',
                'Baliok',
                'Bangkal',
                'Catalunan Grande',
                'Catalunan Pequeño',
                'Daliao',
                'Dumoy',
                'Lizada',
                'Ma-a',
                'Magtuod',
                'Matina Aplaya',
                'Matina Biao',
                'Matina Crossing',
                'Matina Pangi',
                'Mudiang',
                'Mulig',
                'New Valencia',
                'Rafael Castillo',
                'Riverside',
                'San Antonio',
                'Tacunan',
                'Talomo Proper',
                'Talandang',
                'Toril Proper',
                'Ubalde',
                'Wilfredo Aquino',

                // Toril District
                'Bato',
                'Bayabas',
                'Biao Escuela',
                'Carmen',
                'Colosas',
                'Crossing Bayabas',
                'Daliaon Plantation',
                'Eden',
                'Kilate',
                'Lizada',
                'Manuel Guianga',
                'Mudiang',
                'Saloy',
                'Sirawan',
                'Toril Proper',
                'Tugbok',
                'Wines',
            ],
        ];

        foreach ($barangays as $cityName => $bgyList) {
            $city = City::where('name', $cityName)->first();
            if ($city) {
                foreach ($bgyList as $bgy) {
                    Barangay::create([
                        'city_id' => $city->id,
                        'name' => $bgy
                    ]);
                }
            }
        }
    }
}
