<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\User;
use Illuminate\Support\Facades\Hash;
use Carbon\Carbon;

class EmployeeUserSeeder extends Seeder
{
    public function run(): void
    {
        $employees = [
            [
                'employee_id' => 'EMP001',
                'name' => 'Juan S Dela Cruz',
                'first_name' => 'Juan',
                'middle_name' => 'S',
                'last_name' => 'Dela Cruz',
                'suffix' => null,
                'email' => 'juan.delacruz@example.com',
                'phone' => '09171234501',
                'purok_street' => 'Purok 1',
                'city_id' => 'Panabo City',
                'province_id' => 'Davao del Norte',
                'position' => 'Staff',
                'department' => 'HR',
                'employment_status' => 'Permanent',
                'status' => 'active',
                'verification_status' => 'verified',
                'birthday' => '1995-01-15',
            ],
            [
                'employee_id' => 'EMP002',
                'name' => 'Maria L Santos',
                'first_name' => 'Maria',
                'middle_name' => 'L',
                'last_name' => 'Santos',
                'suffix' => null,
                'email' => 'maria.santos@example.com',
                'phone' => '09171234502',
                'purok_street' => 'Purok 2',
                'city_id' => 'Panabo City',
                'province_id' => 'Davao del Norte',
                'position' => 'Assistant',
                'department' => 'Finance',
                'employment_status' => 'Contractual',
                'status' => 'active',
                'verification_status' => 'not-verified',
                'birthday' => '1992-03-22',
            ],
            [
                'employee_id' => 'EMP003',
                'name' => 'Carlos R Garcia',
                'first_name' => 'Carlos',
                'middle_name' => 'R',
                'last_name' => 'Garcia',
                'suffix' => null,
                'email' => 'carlos.garcia@example.com',
                'phone' => '09171234503',
                'purok_street' => 'Purok 3',
                'city_id' => 'Davao City',
                'province_id' => 'Davao del Sur',
                'position' => 'Technician',
                'department' => 'IT',
                'employment_status' => 'Job Order',
                'status' => 'inactive',
                'verification_status' => 'verified',
                'birthday' => '1990-07-18',
            ],
            [
                'employee_id' => 'EMP004',
                'name' => 'Angela P Reyes',
                'first_name' => 'Angela',
                'middle_name' => 'P',
                'last_name' => 'Reyes',
                'suffix' => null,
                'email' => 'angela.reyes@example.com',
                'phone' => '09171234504',
                'purok_street' => 'Purok 4',
                'city_id' => 'Tagum City',
                'province_id' => 'Davao del Norte',
                'position' => 'Manager',
                'department' => 'HR',
                'employment_status' => 'Permanent',
                'status' => 'active',
                'verification_status' => 'verified',
                'birthday' => '1988-09-05',
            ],
            [
                'employee_id' => 'EMP005',
                'name' => 'Ramon T Lopez',
                'first_name' => 'Ramon',
                'middle_name' => 'T',
                'last_name' => 'Lopez',
                'suffix' => null,
                'email' => 'ramon.lopez@example.com',
                'phone' => '09171234505',
                'purok_street' => 'Purok 5',
                'city_id' => 'Panabo City',
                'province_id' => 'Davao del Norte',
                'position' => 'Staff',
                'department' => 'Accounting',
                'employment_status' => 'Contractual',
                'status' => 'inactive',
                'verification_status' => 'not-verified',
                'birthday' => '1994-12-10',
            ],
            [
                'employee_id' => 'EMP006',
                'name' => 'Leah G Martinez',
                'first_name' => 'Leah',
                'middle_name' => 'G',
                'last_name' => 'Martinez',
                'suffix' => null,
                'email' => 'leah.martinez@example.com',
                'phone' => '09171234506',
                'purok_street' => 'Purok 6',
                'city_id' => 'Davao City',
                'province_id' => 'Davao del Sur',
                'position' => 'Analyst',
                'department' => 'IT',
                'employment_status' => 'Permanent',
                'status' => 'active',
                'verification_status' => 'not-verified',
                'birthday' => '1993-11-02',
            ],
            [
                'employee_id' => 'EMP007',
                'name' => 'Mark C Sison',
                'first_name' => 'Mark',
                'middle_name' => 'C',
                'last_name' => 'Sison',
                'suffix' => null,
                'email' => 'mark.sison@example.com',
                'phone' => '09171234507',
                'purok_street' => 'Purok 7',
                'city_id' => 'Panabo City',
                'province_id' => 'Davao del Norte',
                'position' => 'Supervisor',
                'department' => 'Operations',
                'employment_status' => 'Job Order',
                'status' => 'active',
                'verification_status' => 'verified',
                'birthday' => '1989-06-15',
            ],
            [
                'employee_id' => 'EMP008',
                'name' => 'Patricia M De Guzman',
                'first_name' => 'Patricia',
                'middle_name' => 'M',
                'last_name' => 'De Guzman',
                'suffix' => null,
                'email' => 'patricia.deguzman@example.com',
                'phone' => '09171234508',
                'purok_street' => 'Purok 8',
                'city_id' => 'Tagum City',
                'province_id' => 'Davao del Norte',
                'position' => 'Clerk',
                'department' => 'HR',
                'employment_status' => 'Contractual',
                'status' => 'inactive',
                'verification_status' => 'not-verified',
                'birthday' => '1996-04-28',
            ],
            [
                'employee_id' => 'EMP009',
                'name' => 'Jerome B Cruz',
                'first_name' => 'Jerome',
                'middle_name' => 'B',
                'last_name' => 'Cruz',
                'suffix' => null,
                'email' => 'jerome.cruz@example.com',
                'phone' => '09171234509',
                'purok_street' => 'Purok 9',
                'city_id' => 'Panabo City',
                'province_id' => 'Davao del Norte',
                'position' => 'Staff',
                'department' => 'Finance',
                'employment_status' => 'Permanent',
                'status' => 'active',
                'verification_status' => 'verified',
                'birthday' => '1991-08-21',
            ],
            [
                'employee_id' => 'EMP010',
                'name' => 'Monica R Fernandez',
                'first_name' => 'Monica',
                'middle_name' => 'R',
                'last_name' => 'Fernandez',
                'suffix' => null,
                'email' => 'monica.fernandez@example.com',
                'phone' => '09171234510',
                'purok_street' => 'Purok 10',
                'city_id' => 'Davao City',
                'province_id' => 'Davao del Sur',
                'position' => 'Analyst',
                'department' => 'Operations',
                'employment_status' => 'Job Order',
                'status' => 'inactive',
                'verification_status' => 'not-verified',
                'birthday' => '1992-05-14',
            ],
            [
                'employee_id' => 'EMP011',
                'name' => 'Adrian S Velasco',
                'first_name' => 'Adrian',
                'middle_name' => 'S',
                'last_name' => 'Velasco',
                'suffix' => null,
                'email' => 'adrian.velasco@example.com',
                'phone' => '09171234511',
                'purok_street' => 'Purok 11',
                'city_id' => 'Tagum City',
                'province_id' => 'Davao del Norte',
                'position' => 'Staff',
                'department' => 'Finance',
                'employment_status' => 'Permanent',
                'status' => 'active',
                'verification_status' => 'verified',
                'birthday' => '1990-02-10',
            ],
            [
                'employee_id' => 'EMP012',
                'name' => 'Bianca L Torres',
                'first_name' => 'Bianca',
                'middle_name' => 'L',
                'last_name' => 'Torres',
                'suffix' => null,
                'email' => 'bianca.torres@example.com',
                'phone' => '09171234512',
                'purok_street' => 'Purok 12',
                'city_id' => 'Panabo City',
                'province_id' => 'Davao del Norte',
                'position' => 'Assistant',
                'department' => 'HR',
                'employment_status' => 'Contractual',
                'status' => 'inactive',
                'verification_status' => 'not-verified',
                'birthday' => '1993-09-30',
            ],
            [
                'employee_id' => 'EMP013',
                'name' => 'Dennis F Gomez',
                'first_name' => 'Dennis',
                'middle_name' => 'F',
                'last_name' => 'Gomez',
                'suffix' => null,
                'email' => 'dennis.gomez@example.com',
                'phone' => '09171234513',
                'purok_street' => 'Purok 13',
                'city_id' => 'Davao City',
                'province_id' => 'Davao del Sur',
                'position' => 'Supervisor',
                'department' => 'IT',
                'employment_status' => 'Permanent',
                'status' => 'active',
                'verification_status' => 'verified',
                'birthday' => '1987-11-25',
            ],
            [
                'employee_id' => 'EMP014',
                'name' => 'Elena V Santos',
                'first_name' => 'Elena',
                'middle_name' => 'V',
                'last_name' => 'Santos',
                'suffix' => null,
                'email' => 'elena.santos@example.com',
                'phone' => '09171234514',
                'purok_street' => 'Purok 14',
                'city_id' => 'Tagum City',
                'province_id' => 'Davao del Norte',
                'position' => 'Clerk',
                'department' => 'Operations',
                'employment_status' => 'Job Order',
                'status' => 'inactive',
                'verification_status' => 'not-verified',
                'birthday' => '1994-06-17',
            ],
            [
                'employee_id' => 'EMP015',
                'name' => 'Francis D Lopez',
                'first_name' => 'Francis',
                'middle_name' => 'D',
                'last_name' => 'Lopez',
                'suffix' => null,
                'email' => 'francis.lopez@example.com',
                'phone' => '09171234515',
                'purok_street' => 'Purok 15',
                'city_id' => 'Panabo City',
                'province_id' => 'Davao del Norte',
                'position' => 'Staff',
                'department' => 'HR',
                'employment_status' => 'Permanent',
                'status' => 'active',
                'verification_status' => 'verified',
                'birthday' => '1991-12-05',
            ],
        ];

        foreach ($employees as $employee) {
            User::updateOrCreate(
                ['email' => $employee['email']],
                array_merge($employee, ['password' => Hash::make('password123'), 'role' => User::ROLE_EMPLOYEE, 'must_change_password' => true])
            );
        }

        $this->command->info('15 employee users seeded successfully.');
    }
}
