<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\User;
use Illuminate\Support\Facades\Hash;
use Carbon\Carbon;

/**
 * EmployeeUserSeeder
 *
 * Source: ZKTeco/BioTime export — 001_2026_2_MON.xls, sheet "Logs"
 *
 * 24 REGULAR employees  (Dept column = "REGULAR")
 * 31 JOB ORDER employees (Dept column = "JOB ORDER")
 *
 * employee_id = raw device number from the Logs sheet.
 * All records: status=active, verification_status=verified,
 *              email_verified_at=now, must_change_password=true,
 *              password=password123
 */
class EmployeeUserSeeder extends Seeder
{
    public function run(): void
    {
        $employees = [

            // ── REGULAR EMPLOYEES (24) ────────────────────────────────────────
            [
                'employee_id'         => '1',
                'first_name'          => '',
                'middle_name'         => '',
                'last_name'           => 'Jencarnacion',
                'suffix'              => null,
                'name'                => 'Jencarnacion',
                'email'               => 'emp.jencarnacion@ati11.example.com',
                'phone'               => null,
                'purok_street'        => null,
                'region_id'           => null,
                'province_id'         => null,
                'city_id'             => null,
                'barangay_id'         => null,
                'birthday'            => null,
                'position'            => 'Staff',
                'department'          => 'ATI 11',
                'employment_status'   => 'Permanent',
                'status'              => 'active',
                'verification_status' => 'verified',
                'role'                => User::ROLE_REGULAR,
            ],
            [
                'employee_id'         => '2',
                'first_name'          => 'R',
                'middle_name'         => '',
                'last_name'           => 'Rubis',
                'suffix'              => null,
                'name'                => 'R Rubis',
                'email'               => 'r.rubis@ati11.example.com',
                'phone'               => null,
                'purok_street'        => null,
                'region_id'           => null,
                'province_id'         => null,
                'city_id'             => null,
                'barangay_id'         => null,
                'birthday'            => null,
                'position'            => 'Staff',
                'department'          => 'ATI 11',
                'employment_status'   => 'Permanent',
                'status'              => 'active',
                'verification_status' => 'verified',
                'role'                => User::ROLE_REGULAR,
            ],
            [
                'employee_id'         => '3',
                'first_name'          => 'R',
                'middle_name'         => '',
                'last_name'           => 'Zamora',
                'suffix'              => null,
                'name'                => 'R Zamora',
                'email'               => 'r.zamora@ati11.example.com',
                'phone'               => null,
                'purok_street'        => null,
                'region_id'           => null,
                'province_id'         => null,
                'city_id'             => null,
                'barangay_id'         => null,
                'birthday'            => null,
                'position'            => 'Staff',
                'department'          => 'ATI 11',
                'employment_status'   => 'Permanent',
                'status'              => 'active',
                'verification_status' => 'verified',
                'role'                => User::ROLE_REGULAR,
            ],
            [
                'employee_id'         => '5',
                'first_name'          => 'P',
                'middle_name'         => 'J',
                'last_name'           => 'Mahumot',
                'suffix'              => null,
                'name'                => 'P J Mahumot',
                'email'               => 'p.mahumot@ati11.example.com',
                'phone'               => null,
                'purok_street'        => null,
                'region_id'           => null,
                'province_id'         => null,
                'city_id'             => null,
                'barangay_id'         => null,
                'birthday'            => null,
                'position'            => 'Staff',
                'department'          => 'ATI 11',
                'employment_status'   => 'Permanent',
                'status'              => 'active',
                'verification_status' => 'verified',
                'role'                => User::ROLE_REGULAR,
            ],
            [
                'employee_id'         => '6',
                'first_name'          => 'O',
                'middle_name'         => 'A',
                'last_name'           => 'Sanchez',
                'suffix'              => null,
                'name'                => 'O A Sanchez',
                'email'               => 'o.sanchez@ati11.example.com',
                'phone'               => null,
                'purok_street'        => null,
                'region_id'           => null,
                'province_id'         => null,
                'city_id'             => null,
                'barangay_id'         => null,
                'birthday'            => null,
                'position'            => 'Staff',
                'department'          => 'ATI 11',
                'employment_status'   => 'Permanent',
                'status'              => 'active',
                'verification_status' => 'verified',
                'role'                => User::ROLE_REGULAR,
            ],
            [
                'employee_id'         => '7',
                'first_name'          => 'L',
                'middle_name'         => '',
                'last_name'           => 'Camarines',
                'suffix'              => null,
                'name'                => 'L Camarines',
                'email'               => 'l.camarines@ati11.example.com',
                'phone'               => null,
                'purok_street'        => null,
                'region_id'           => null,
                'province_id'         => null,
                'city_id'             => null,
                'barangay_id'         => null,
                'birthday'            => null,
                'position'            => 'Staff',
                'department'          => 'ATI 11',
                'employment_status'   => 'Permanent',
                'status'              => 'active',
                'verification_status' => 'verified',
                'role'                => User::ROLE_REGULAR,
            ],
            [
                'employee_id'         => '8',
                'first_name'          => 'E',
                'middle_name'         => 'L',
                'last_name'           => 'Malazarte',
                'suffix'              => null,
                'name'                => 'E L Malazarte',
                'email'               => 'e.malazarte@ati11.example.com',
                'phone'               => null,
                'purok_street'        => null,
                'region_id'           => null,
                'province_id'         => null,
                'city_id'             => null,
                'barangay_id'         => null,
                'birthday'            => null,
                'position'            => 'Staff',
                'department'          => 'ATI 11',
                'employment_status'   => 'Permanent',
                'status'              => 'active',
                'verification_status' => 'verified',
                'role'                => User::ROLE_REGULAR,
            ],
            [
                'employee_id'         => '9',
                'first_name'          => 'B',
                'middle_name'         => '',
                'last_name'           => 'Lanit',
                'suffix'              => null,
                'name'                => 'B Lanit',
                'email'               => 'b.lanit@ati11.example.com',
                'phone'               => null,
                'purok_street'        => null,
                'region_id'           => null,
                'province_id'         => null,
                'city_id'             => null,
                'barangay_id'         => null,
                'birthday'            => null,
                'position'            => 'Staff',
                'department'          => 'ATI 11',
                'employment_status'   => 'Permanent',
                'status'              => 'active',
                'verification_status' => 'verified',
                'role'                => User::ROLE_REGULAR,
            ],
            [
                'employee_id'         => '13',
                'first_name'          => 'J',
                'middle_name'         => '',
                'last_name'           => 'Reyes',
                'suffix'              => null,
                'name'                => 'J Reyes',
                'email'               => 'j.reyes@ati11.example.com',
                'phone'               => null,
                'purok_street'        => null,
                'region_id'           => null,
                'province_id'         => null,
                'city_id'             => null,
                'barangay_id'         => null,
                'birthday'            => null,
                'position'            => 'Staff',
                'department'          => 'ATI 11',
                'employment_status'   => 'Permanent',
                'status'              => 'active',
                'verification_status' => 'verified',
                'role'                => User::ROLE_REGULAR,
            ],
            [
                'employee_id'         => '14',
                'first_name'          => 'M',
                'middle_name'         => 'CR',
                'last_name'           => 'Besario',
                'suffix'              => null,
                'name'                => 'M CR Besario',
                'email'               => 'm.besario@ati11.example.com',
                'phone'               => null,
                'purok_street'        => null,
                'region_id'           => null,
                'province_id'         => null,
                'city_id'             => null,
                'barangay_id'         => null,
                'birthday'            => null,
                'position'            => 'Staff',
                'department'          => 'ATI 11',
                'employment_status'   => 'Permanent',
                'status'              => 'active',
                'verification_status' => 'verified',
                'role'                => User::ROLE_REGULAR,
            ],
            [
                'employee_id'         => '15',
                'first_name'          => 'A',
                'middle_name'         => '',
                'last_name'           => 'Mapayo',
                'suffix'              => null,
                'name'                => 'A Mapayo',
                'email'               => 'a.mapayo@ati11.example.com',
                'phone'               => null,
                'purok_street'        => null,
                'region_id'           => null,
                'province_id'         => null,
                'city_id'             => null,
                'barangay_id'         => null,
                'birthday'            => null,
                'position'            => 'Staff',
                'department'          => 'ATI 11',
                'employment_status'   => 'Permanent',
                'status'              => 'active',
                'verification_status' => 'verified',
                'role'                => User::ROLE_REGULAR,
            ],
            [
                'employee_id'         => '16',
                'first_name'          => 'R',
                'middle_name'         => '',
                'last_name'           => 'Bentiroso',
                'suffix'              => null,
                'name'                => 'R Bentiroso',
                'email'               => 'r.bentiroso@ati11.example.com',
                'phone'               => null,
                'purok_street'        => null,
                'region_id'           => null,
                'province_id'         => null,
                'city_id'             => null,
                'barangay_id'         => null,
                'birthday'            => null,
                'position'            => 'Staff',
                'department'          => 'ATI 11',
                'employment_status'   => 'Permanent',
                'status'              => 'active',
                'verification_status' => 'verified',
                'role'                => User::ROLE_REGULAR,
            ],
            [
                'employee_id'         => '18',
                'first_name'          => 'M',
                'middle_name'         => '',
                'last_name'           => 'Nomus',
                'suffix'              => null,
                'name'                => 'M Nomus',
                'email'               => 'm.nomus@ati11.example.com',
                'phone'               => null,
                'purok_street'        => null,
                'region_id'           => null,
                'province_id'         => null,
                'city_id'             => null,
                'barangay_id'         => null,
                'birthday'            => null,
                'position'            => 'Staff',
                'department'          => 'ATI 11',
                'employment_status'   => 'Permanent',
                'status'              => 'active',
                'verification_status' => 'verified',
                'role'                => User::ROLE_REGULAR,
            ],
            [
                'employee_id'         => '19',
                'first_name'          => 'E',
                'middle_name'         => 'C',
                'last_name'           => 'Jimenez',
                'suffix'              => null,
                'name'                => 'E C Jimenez',
                'email'               => 'e.jimenez@ati11.example.com',
                'phone'               => null,
                'purok_street'        => null,
                'region_id'           => null,
                'province_id'         => null,
                'city_id'             => null,
                'barangay_id'         => null,
                'birthday'            => null,
                'position'            => 'Staff',
                'department'          => 'ATI 11',
                'employment_status'   => 'Permanent',
                'status'              => 'active',
                'verification_status' => 'verified',
                'role'                => User::ROLE_REGULAR,
            ],
            [
                'employee_id'         => '24',
                'first_name'          => 'O',
                'middle_name'         => 'D',
                'last_name'           => 'Gatus',
                'suffix'              => null,
                'name'                => 'O D Gatus',
                'email'               => 'o.gatus@ati11.example.com',
                'phone'               => null,
                'purok_street'        => null,
                'region_id'           => null,
                'province_id'         => null,
                'city_id'             => null,
                'barangay_id'         => null,
                'birthday'            => null,
                'position'            => 'Staff',
                'department'          => 'ATI 11',
                'employment_status'   => 'Permanent',
                'status'              => 'active',
                'verification_status' => 'verified',
                'role'                => User::ROLE_REGULAR,
            ],
            [
                'employee_id'         => '28',
                'first_name'          => 'L',
                'middle_name'         => '',
                'last_name'           => 'Leopoldo',
                'suffix'              => null,
                'name'                => 'L Leopoldo',
                'email'               => 'l.leopoldo@ati11.example.com',
                'phone'               => null,
                'purok_street'        => null,
                'region_id'           => null,
                'province_id'         => null,
                'city_id'             => null,
                'barangay_id'         => null,
                'birthday'            => null,
                'position'            => 'Staff',
                'department'          => 'ATI 11',
                'employment_status'   => 'Permanent',
                'status'              => 'active',
                'verification_status' => 'verified',
                'role'                => User::ROLE_REGULAR,
            ],
            [
                'employee_id'         => '37',
                'first_name'          => 'N',
                'middle_name'         => '',
                'last_name'           => 'Lumandong',
                'suffix'              => null,
                'name'                => 'N Lumandong',
                'email'               => 'n.lumandong@ati11.example.com',
                'phone'               => null,
                'purok_street'        => null,
                'region_id'           => null,
                'province_id'         => null,
                'city_id'             => null,
                'barangay_id'         => null,
                'birthday'            => null,
                'position'            => 'Staff',
                'department'          => 'ATI 11',
                'employment_status'   => 'Permanent',
                'status'              => 'active',
                'verification_status' => 'verified',
                'role'                => User::ROLE_REGULAR,
            ],
            [
                'employee_id'         => '40',
                'first_name'          => 'J',
                'middle_name'         => '',
                'last_name'           => 'Carpentero',
                'suffix'              => null,
                'name'                => 'J Carpentero',
                'email'               => 'j.carpentero@ati11.example.com',
                'phone'               => null,
                'purok_street'        => null,
                'region_id'           => null,
                'province_id'         => null,
                'city_id'             => null,
                'barangay_id'         => null,
                'birthday'            => null,
                'position'            => 'Staff',
                'department'          => 'ATI 11',
                'employment_status'   => 'Permanent',
                'status'              => 'active',
                'verification_status' => 'verified',
                'role'                => User::ROLE_REGULAR,
            ],
            [
                'employee_id'         => '41',
                'first_name'          => 'C',
                'middle_name'         => 'V',
                'last_name'           => 'Canete',
                'suffix'              => null,
                'name'                => 'C V Canete',
                'email'               => 'c.canete@ati11.example.com',
                'phone'               => null,
                'purok_street'        => null,
                'region_id'           => null,
                'province_id'         => null,
                'city_id'             => null,
                'barangay_id'         => null,
                'birthday'            => null,
                'position'            => 'Staff',
                'department'          => 'ATI 11',
                'employment_status'   => 'Permanent',
                'status'              => 'active',
                'verification_status' => 'verified',
                'role'                => User::ROLE_REGULAR,
            ],
            [
                'employee_id'         => '42',
                'first_name'          => 'O',
                'middle_name'         => 'B',
                'last_name'           => 'Dalam',
                'suffix'              => null,
                'name'                => 'O B Dalam',
                'email'               => 'o.dalam@ati11.example.com',
                'phone'               => null,
                'purok_street'        => null,
                'region_id'           => null,
                'province_id'         => null,
                'city_id'             => null,
                'barangay_id'         => null,
                'birthday'            => null,
                'position'            => 'Staff',
                'department'          => 'ATI 11',
                'employment_status'   => 'Permanent',
                'status'              => 'active',
                'verification_status' => 'verified',
                'role'                => User::ROLE_REGULAR,
            ],
            [
                'employee_id'         => '53',
                'first_name'          => 'A',
                'middle_name'         => '',
                'last_name'           => 'Abastillas',
                'suffix'              => null,
                'name'                => 'A Abastillas',
                'email'               => 'a.abastillas@ati11.example.com',
                'phone'               => null,
                'purok_street'        => null,
                'region_id'           => null,
                'province_id'         => null,
                'city_id'             => null,
                'barangay_id'         => null,
                'birthday'            => null,
                'position'            => 'Staff',
                'department'          => 'ATI 11',
                'employment_status'   => 'Permanent',
                'status'              => 'active',
                'verification_status' => 'verified',
                'role'                => User::ROLE_REGULAR,
            ],
            [
                'employee_id'         => '58',
                'first_name'          => 'J',
                'middle_name'         => '',
                'last_name'           => 'Saludares',
                'suffix'              => null,
                'name'                => 'J Saludares',
                'email'               => 'j.saludares@ati11.example.com',
                'phone'               => null,
                'purok_street'        => null,
                'region_id'           => null,
                'province_id'         => null,
                'city_id'             => null,
                'barangay_id'         => null,
                'birthday'            => null,
                'position'            => 'Staff',
                'department'          => 'ATI 11',
                'employment_status'   => 'Permanent',
                'status'              => 'active',
                'verification_status' => 'verified',
                'role'                => User::ROLE_REGULAR,
            ],
            [
                'employee_id'         => '63',
                'first_name'          => 'A',
                'middle_name'         => 'R',
                'last_name'           => 'Nebreja',
                'suffix'              => null,
                'name'                => 'A R Nebreja',
                'email'               => 'a.nebreja@ati11.example.com',
                'phone'               => null,
                'purok_street'        => null,
                'region_id'           => null,
                'province_id'         => null,
                'city_id'             => null,
                'barangay_id'         => null,
                'birthday'            => null,
                'position'            => 'Staff',
                'department'          => 'ATI 11',
                'employment_status'   => 'Permanent',
                'status'              => 'active',
                'verification_status' => 'verified',
                'role'                => User::ROLE_REGULAR,
            ],
            [
                'employee_id'         => '67',
                'first_name'          => 'M',
                'middle_name'         => '',
                'last_name'           => 'Encio',
                'suffix'              => null,
                'name'                => 'M Encio',
                'email'               => 'm.encio@ati11.example.com',
                'phone'               => null,
                'purok_street'        => null,
                'region_id'           => null,
                'province_id'         => null,
                'city_id'             => null,
                'barangay_id'         => null,
                'birthday'            => null,
                'position'            => 'Staff',
                'department'          => 'ATI 11',
                'employment_status'   => 'Permanent',
                'status'              => 'active',
                'verification_status' => 'verified',
                'role'                => User::ROLE_REGULAR,
            ],

            // ── JOB ORDER EMPLOYEES (31) ──────────────────────────────────────
            [
                'employee_id'         => '4',
                'first_name'          => 'M',
                'middle_name'         => '',
                'last_name'           => 'Castro',
                'suffix'              => null,
                'name'                => 'M Castro',
                'email'               => 'm.castro@ati11.example.com',
                'phone'               => null,
                'purok_street'        => null,
                'region_id'           => null,
                'province_id'         => null,
                'city_id'             => null,
                'barangay_id'         => null,
                'birthday'            => null,
                'position'            => 'Job Order',
                'department'          => 'ATI 11',
                'employment_status'   => 'Job Order',
                'status'              => 'active',
                'verification_status' => 'verified',
                'role'                => User::ROLE_JOB_ORDER,
            ],
            [
                'employee_id'         => '10',
                'first_name'          => 'R',
                'middle_name'         => 'J',
                'last_name'           => 'Basanez',
                'suffix'              => null,
                'name'                => 'R J Basanez',
                'email'               => 'r.basanez@ati11.example.com',
                'phone'               => null,
                'purok_street'        => null,
                'region_id'           => null,
                'province_id'         => null,
                'city_id'             => null,
                'barangay_id'         => null,
                'birthday'            => null,
                'position'            => 'Job Order',
                'department'          => 'ATI 11',
                'employment_status'   => 'Job Order',
                'status'              => 'active',
                'verification_status' => 'verified',
                'role'                => User::ROLE_JOB_ORDER,
            ],
            [
                'employee_id'         => '11',
                'first_name'          => 'A',
                'middle_name'         => 'M',
                'last_name'           => 'Gabriedo',
                'suffix'              => null,
                'name'                => 'A M Gabriedo',
                'email'               => 'a.gabriedo@ati11.example.com',
                'phone'               => null,
                'purok_street'        => null,
                'region_id'           => null,
                'province_id'         => null,
                'city_id'             => null,
                'barangay_id'         => null,
                'birthday'            => null,
                'position'            => 'Job Order',
                'department'          => 'ATI 11',
                'employment_status'   => 'Job Order',
                'status'              => 'active',
                'verification_status' => 'verified',
                'role'                => User::ROLE_JOB_ORDER,
            ],
            [
                'employee_id'         => '12',
                'first_name'          => 'K',
                'middle_name'         => '',
                'last_name'           => 'Pabilan',
                'suffix'              => null,
                'name'                => 'K Pabilan',
                'email'               => 'k.pabilan@ati11.example.com',
                'phone'               => null,
                'purok_street'        => null,
                'region_id'           => null,
                'province_id'         => null,
                'city_id'             => null,
                'barangay_id'         => null,
                'birthday'            => null,
                'position'            => 'Job Order',
                'department'          => 'ATI 11',
                'employment_status'   => 'Job Order',
                'status'              => 'active',
                'verification_status' => 'verified',
                'role'                => User::ROLE_JOB_ORDER,
            ],
            [
                'employee_id'         => '17',
                'first_name'          => 'J',
                'middle_name'         => '',
                'last_name'           => 'Castor',
                'suffix'              => null,
                'name'                => 'J Castor',
                'email'               => 'j.castor@ati11.example.com',
                'phone'               => null,
                'purok_street'        => null,
                'region_id'           => null,
                'province_id'         => null,
                'city_id'             => null,
                'barangay_id'         => null,
                'birthday'            => null,
                'position'            => 'Job Order',
                'department'          => 'ATI 11',
                'employment_status'   => 'Job Order',
                'status'              => 'active',
                'verification_status' => 'verified',
                'role'                => User::ROLE_JOB_ORDER,
            ],
            [
                'employee_id'         => '27',
                'first_name'          => 'L',
                'middle_name'         => '',
                'last_name'           => 'Tingocia',
                'suffix'              => null,
                'name'                => 'L Tingocia',
                'email'               => 'l.tingocia@ati11.example.com',
                'phone'               => null,
                'purok_street'        => null,
                'region_id'           => null,
                'province_id'         => null,
                'city_id'             => null,
                'barangay_id'         => null,
                'birthday'            => null,
                'position'            => 'Job Order',
                'department'          => 'ATI 11',
                'employment_status'   => 'Job Order',
                'status'              => 'active',
                'verification_status' => 'verified',
                'role'                => User::ROLE_JOB_ORDER,
            ],
            [
                'employee_id'         => '30',
                'first_name'          => 'J',
                'middle_name'         => '',
                'last_name'           => 'Maligro',
                'suffix'              => null,
                'name'                => 'J Maligro',
                'email'               => 'j.maligro@ati11.example.com',
                'phone'               => null,
                'purok_street'        => null,
                'region_id'           => null,
                'province_id'         => null,
                'city_id'             => null,
                'barangay_id'         => null,
                'birthday'            => null,
                'position'            => 'Job Order',
                'department'          => 'ATI 11',
                'employment_status'   => 'Job Order',
                'status'              => 'active',
                'verification_status' => 'verified',
                'role'                => User::ROLE_JOB_ORDER,
            ],
            [
                'employee_id'         => '39',
                'first_name'          => 'M',
                'middle_name'         => '',
                'last_name'           => 'Kapa',
                'suffix'              => null,
                'name'                => 'M Kapa',
                'email'               => 'm.kapa@ati11.example.com',
                'phone'               => null,
                'purok_street'        => null,
                'region_id'           => null,
                'province_id'         => null,
                'city_id'             => null,
                'barangay_id'         => null,
                'birthday'            => null,
                'position'            => 'Job Order',
                'department'          => 'ATI 11',
                'employment_status'   => 'Job Order',
                'status'              => 'active',
                'verification_status' => 'verified',
                'role'                => User::ROLE_JOB_ORDER,
            ],
            [
                'employee_id'         => '44',
                'first_name'          => 'M',
                'middle_name'         => '',
                'last_name'           => 'Mating',
                'suffix'              => null,
                'name'                => 'M Mating',
                'email'               => 'm.mating@ati11.example.com',
                'phone'               => null,
                'purok_street'        => null,
                'region_id'           => null,
                'province_id'         => null,
                'city_id'             => null,
                'barangay_id'         => null,
                'birthday'            => null,
                'position'            => 'Job Order',
                'department'          => 'ATI 11',
                'employment_status'   => 'Job Order',
                'status'              => 'active',
                'verification_status' => 'verified',
                'role'                => User::ROLE_JOB_ORDER,
            ],
            [
                'employee_id'         => '45',
                'first_name'          => 'J',
                'middle_name'         => '',
                'last_name'           => 'Bartiana',
                'suffix'              => null,
                'name'                => 'J Bartiana',
                'email'               => 'j.bartiana@ati11.example.com',
                'phone'               => null,
                'purok_street'        => null,
                'region_id'           => null,
                'province_id'         => null,
                'city_id'             => null,
                'barangay_id'         => null,
                'birthday'            => null,
                'position'            => 'Job Order',
                'department'          => 'ATI 11',
                'employment_status'   => 'Job Order',
                'status'              => 'active',
                'verification_status' => 'verified',
                'role'                => User::ROLE_JOB_ORDER,
            ],
            [
                'employee_id'         => '47',
                'first_name'          => 'M',
                'middle_name'         => '',
                'last_name'           => 'Nacolangga',
                'suffix'              => null,
                'name'                => 'M Nacolangga',
                'email'               => 'm.nacolangga@ati11.example.com',
                'phone'               => null,
                'purok_street'        => null,
                'region_id'           => null,
                'province_id'         => null,
                'city_id'             => null,
                'barangay_id'         => null,
                'birthday'            => null,
                'position'            => 'Job Order',
                'department'          => 'ATI 11',
                'employment_status'   => 'Job Order',
                'status'              => 'active',
                'verification_status' => 'verified',
                'role'                => User::ROLE_JOB_ORDER,
            ],
            [
                'employee_id'         => '48',
                'first_name'          => 'O',
                'middle_name'         => '',
                'last_name'           => 'Cansing',
                'suffix'              => null,
                'name'                => 'O Cansing',
                'email'               => 'o.cansing@ati11.example.com',
                'phone'               => null,
                'purok_street'        => null,
                'region_id'           => null,
                'province_id'         => null,
                'city_id'             => null,
                'barangay_id'         => null,
                'birthday'            => null,
                'position'            => 'Job Order',
                'department'          => 'ATI 11',
                'employment_status'   => 'Job Order',
                'status'              => 'active',
                'verification_status' => 'verified',
                'role'                => User::ROLE_JOB_ORDER,
            ],
            [
                'employee_id'         => '49',
                'first_name'          => 'J',
                'middle_name'         => 'A',
                'last_name'           => 'Guitones',
                'suffix'              => null,
                'name'                => 'J A Guitones',
                'email'               => 'j.guitones@ati11.example.com',
                'phone'               => null,
                'purok_street'        => null,
                'region_id'           => null,
                'province_id'         => null,
                'city_id'             => null,
                'barangay_id'         => null,
                'birthday'            => null,
                'position'            => 'Job Order',
                'department'          => 'ATI 11',
                'employment_status'   => 'Job Order',
                'status'              => 'active',
                'verification_status' => 'verified',
                'role'                => User::ROLE_JOB_ORDER,
            ],
            [
                'employee_id'         => '50',
                'first_name'          => 'L',
                'middle_name'         => '',
                'last_name'           => 'Buenaobra',
                'suffix'              => null,
                'name'                => 'L Buenaobra',
                'email'               => 'l.buenaobra@ati11.example.com',
                'phone'               => null,
                'purok_street'        => null,
                'region_id'           => null,
                'province_id'         => null,
                'city_id'             => null,
                'barangay_id'         => null,
                'birthday'            => null,
                'position'            => 'Job Order',
                'department'          => 'ATI 11',
                'employment_status'   => 'Job Order',
                'status'              => 'active',
                'verification_status' => 'verified',
                'role'                => User::ROLE_JOB_ORDER,
            ],
            [
                'employee_id'         => '51',
                'first_name'          => 'B',
                'middle_name'         => 'F',
                'last_name'           => 'Cachuela',
                'suffix'              => null,
                'name'                => 'B F Cachuela',
                'email'               => 'b.cachuela@ati11.example.com',
                'phone'               => null,
                'purok_street'        => null,
                'region_id'           => null,
                'province_id'         => null,
                'city_id'             => null,
                'barangay_id'         => null,
                'birthday'            => null,
                'position'            => 'Job Order',
                'department'          => 'ATI 11',
                'employment_status'   => 'Job Order',
                'status'              => 'active',
                'verification_status' => 'verified',
                'role'                => User::ROLE_JOB_ORDER,
            ],
            [
                'employee_id'         => '52',
                'first_name'          => 'Jen',
                'middle_name'         => '',
                'last_name'           => 'Montec',
                'suffix'              => null,
                'name'                => 'Jen Montec',
                'email'               => 'j.montec@ati11.example.com',
                'phone'               => null,
                'purok_street'        => null,
                'region_id'           => null,
                'province_id'         => null,
                'city_id'             => null,
                'barangay_id'         => null,
                'birthday'            => null,
                'position'            => 'Job Order',
                'department'          => 'ATI 11',
                'employment_status'   => 'Job Order',
                'status'              => 'active',
                'verification_status' => 'verified',
                'role'                => User::ROLE_JOB_ORDER,
            ],
            [
                'employee_id'         => '54',
                'first_name'          => 'I',
                'middle_name'         => '',
                'last_name'           => 'Ladera',
                'suffix'              => null,
                'name'                => 'I Ladera',
                'email'               => 'i.ladera@ati11.example.com',
                'phone'               => null,
                'purok_street'        => null,
                'region_id'           => null,
                'province_id'         => null,
                'city_id'             => null,
                'barangay_id'         => null,
                'birthday'            => null,
                'position'            => 'Job Order',
                'department'          => 'ATI 11',
                'employment_status'   => 'Job Order',
                'status'              => 'active',
                'verification_status' => 'verified',
                'role'                => User::ROLE_JOB_ORDER,
            ],
            [
                'employee_id'         => '55',
                'first_name'          => 'C',
                'middle_name'         => '',
                'last_name'           => 'Balmores',
                'suffix'              => null,
                'name'                => 'C Balmores',
                'email'               => 'c.balmores@ati11.example.com',
                'phone'               => null,
                'purok_street'        => null,
                'region_id'           => null,
                'province_id'         => null,
                'city_id'             => null,
                'barangay_id'         => null,
                'birthday'            => null,
                'position'            => 'Job Order',
                'department'          => 'ATI 11',
                'employment_status'   => 'Job Order',
                'status'              => 'active',
                'verification_status' => 'verified',
                'role'                => User::ROLE_JOB_ORDER,
            ],
            [
                'employee_id'         => '56',
                'first_name'          => 'A',
                'middle_name'         => '',
                'last_name'           => 'Flores',
                'suffix'              => null,
                'name'                => 'A Flores',
                'email'               => 'a.flores@ati11.example.com',
                'phone'               => null,
                'purok_street'        => null,
                'region_id'           => null,
                'province_id'         => null,
                'city_id'             => null,
                'barangay_id'         => null,
                'birthday'            => null,
                'position'            => 'Job Order',
                'department'          => 'ATI 11',
                'employment_status'   => 'Job Order',
                'status'              => 'active',
                'verification_status' => 'verified',
                'role'                => User::ROLE_JOB_ORDER,
            ],
            [
                'employee_id'         => '57',
                'first_name'          => 'M',
                'middle_name'         => '',
                'last_name'           => 'Gallardo',
                'suffix'              => null,
                'name'                => 'M Gallardo',
                'email'               => 'm.gallardo@ati11.example.com',
                'phone'               => null,
                'purok_street'        => null,
                'region_id'           => null,
                'province_id'         => null,
                'city_id'             => null,
                'barangay_id'         => null,
                'birthday'            => null,
                'position'            => 'Job Order',
                'department'          => 'ATI 11',
                'employment_status'   => 'Job Order',
                'status'              => 'active',
                'verification_status' => 'verified',
                'role'                => User::ROLE_JOB_ORDER,
            ],
            [
                'employee_id'         => '60',
                'first_name'          => 'G',
                'middle_name'         => '',
                'last_name'           => 'Salazar',
                'suffix'              => null,
                'name'                => 'G Salazar',
                'email'               => 'g.salazar@ati11.example.com',
                'phone'               => null,
                'purok_street'        => null,
                'region_id'           => null,
                'province_id'         => null,
                'city_id'             => null,
                'barangay_id'         => null,
                'birthday'            => null,
                'position'            => 'Job Order',
                'department'          => 'ATI 11',
                'employment_status'   => 'Job Order',
                'status'              => 'active',
                'verification_status' => 'verified',
                'role'                => User::ROLE_JOB_ORDER,
            ],
            [
                'employee_id'         => '61',
                'first_name'          => 'R',
                'middle_name'         => '',
                'last_name'           => 'Villaraza',
                'suffix'              => null,
                'name'                => 'R Villaraza',
                'email'               => 'r.villaraza@ati11.example.com',
                'phone'               => null,
                'purok_street'        => null,
                'region_id'           => null,
                'province_id'         => null,
                'city_id'             => null,
                'barangay_id'         => null,
                'birthday'            => null,
                'position'            => 'Job Order',
                'department'          => 'ATI 11',
                'employment_status'   => 'Job Order',
                'status'              => 'active',
                'verification_status' => 'verified',
                'role'                => User::ROLE_JOB_ORDER,
            ],
            [
                'employee_id'         => '62',
                'first_name'          => 'J',
                'middle_name'         => '',
                'last_name'           => 'Sumambot',
                'suffix'              => null,
                'name'                => 'J Sumambot',
                'email'               => 'j.sumambot@ati11.example.com',
                'phone'               => null,
                'purok_street'        => null,
                'region_id'           => null,
                'province_id'         => null,
                'city_id'             => null,
                'barangay_id'         => null,
                'birthday'            => null,
                'position'            => 'Job Order',
                'department'          => 'ATI 11',
                'employment_status'   => 'Job Order',
                'status'              => 'active',
                'verification_status' => 'verified',
                'role'                => User::ROLE_JOB_ORDER,
            ],
            [
                'employee_id'         => '64',
                'first_name'          => 'F',
                'middle_name'         => 'T',
                'last_name'           => 'Parreno',
                'suffix'              => null,
                'name'                => 'F T Parreno',
                'email'               => 'f.parreno@ati11.example.com',
                'phone'               => null,
                'purok_street'        => null,
                'region_id'           => null,
                'province_id'         => null,
                'city_id'             => null,
                'barangay_id'         => null,
                'birthday'            => null,
                'position'            => 'Job Order',
                'department'          => 'ATI 11',
                'employment_status'   => 'Job Order',
                'status'              => 'active',
                'verification_status' => 'verified',
                'role'                => User::ROLE_JOB_ORDER,
            ],
            [
                'employee_id'         => '65',
                'first_name'          => 'C',
                'middle_name'         => '',
                'last_name'           => 'Perez',
                'suffix'              => null,
                'name'                => 'C Perez',
                'email'               => 'c.perez@ati11.example.com',
                'phone'               => null,
                'purok_street'        => null,
                'region_id'           => null,
                'province_id'         => null,
                'city_id'             => null,
                'barangay_id'         => null,
                'birthday'            => null,
                'position'            => 'Job Order',
                'department'          => 'ATI 11',
                'employment_status'   => 'Job Order',
                'status'              => 'active',
                'verification_status' => 'verified',
                'role'                => User::ROLE_JOB_ORDER,
            ],
            [
                'employee_id'         => '66',
                'first_name'          => 'C',
                'middle_name'         => '',
                'last_name'           => 'Lacida',
                'suffix'              => null,
                'name'                => 'C Lacida',
                'email'               => 'c.lacida@ati11.example.com',
                'phone'               => null,
                'purok_street'        => null,
                'region_id'           => null,
                'province_id'         => null,
                'city_id'             => null,
                'barangay_id'         => null,
                'birthday'            => null,
                'position'            => 'Job Order',
                'department'          => 'ATI 11',
                'employment_status'   => 'Job Order',
                'status'              => 'active',
                'verification_status' => 'verified',
                'role'                => User::ROLE_JOB_ORDER,
            ],
            [
                'employee_id'         => '68',
                'first_name'          => 'W',
                'middle_name'         => 'D',
                'last_name'           => 'Reyes',
                'suffix'              => null,
                'name'                => 'W D Reyes',
                'email'               => 'wd.reyes@ati11.example.com',
                'phone'               => null,
                'purok_street'        => null,
                'region_id'           => null,
                'province_id'         => null,
                'city_id'             => null,
                'barangay_id'         => null,
                'birthday'            => null,
                'position'            => 'Job Order',
                'department'          => 'ATI 11',
                'employment_status'   => 'Job Order',
                'status'              => 'active',
                'verification_status' => 'verified',
                'role'                => User::ROLE_JOB_ORDER,
            ],
            [
                'employee_id'         => '69',
                'first_name'          => 'C',
                'middle_name'         => '',
                'last_name'           => 'Pagarigan',
                'suffix'              => null,
                'name'                => 'C Pagarigan',
                'email'               => 'c.pagarigan@ati11.example.com',
                'phone'               => null,
                'purok_street'        => null,
                'region_id'           => null,
                'province_id'         => null,
                'city_id'             => null,
                'barangay_id'         => null,
                'birthday'            => null,
                'position'            => 'Job Order',
                'department'          => 'ATI 11',
                'employment_status'   => 'Job Order',
                'status'              => 'active',
                'verification_status' => 'verified',
                'role'                => User::ROLE_JOB_ORDER,
            ],
            [
                'employee_id'         => '94',
                'first_name'          => 'C',
                'middle_name'         => '',
                'last_name'           => 'Dela Cruz',
                'suffix'              => null,
                'name'                => 'C Dela Cruz',
                'email'               => 'c.delacruz@ati11.example.com',
                'phone'               => null,
                'purok_street'        => null,
                'region_id'           => null,
                'province_id'         => null,
                'city_id'             => null,
                'barangay_id'         => null,
                'birthday'            => null,
                'position'            => 'Job Order',
                'department'          => 'ATI 11',
                'employment_status'   => 'Job Order',
                'status'              => 'active',
                'verification_status' => 'verified',
                'role'                => User::ROLE_JOB_ORDER,
            ],
            [
                'employee_id'         => '95',
                'first_name'          => 'R',
                'middle_name'         => '',
                'last_name'           => 'Barte',
                'suffix'              => null,
                'name'                => 'R Barte',
                'email'               => 'r.barte@ati11.example.com',
                'phone'               => null,
                'purok_street'        => null,
                'region_id'           => null,
                'province_id'         => null,
                'city_id'             => null,
                'barangay_id'         => null,
                'birthday'            => null,
                'position'            => 'Job Order',
                'department'          => 'ATI 11',
                'employment_status'   => 'Job Order',
                'status'              => 'active',
                'verification_status' => 'verified',
                'role'                => User::ROLE_JOB_ORDER,
            ],
            [
                'employee_id'         => '96',
                'first_name'          => 'D',
                'middle_name'         => '',
                'last_name'           => 'Manlangan',
                'suffix'              => null,
                'name'                => 'D Manlangan',
                'email'               => 'd.manlangan@ati11.example.com',
                'phone'               => null,
                'purok_street'        => null,
                'region_id'           => null,
                'province_id'         => null,
                'city_id'             => null,
                'barangay_id'         => null,
                'birthday'            => null,
                'position'            => 'Job Order',
                'department'          => 'ATI 11',
                'employment_status'   => 'Job Order',
                'status'              => 'active',
                'verification_status' => 'verified',
                'role'                => User::ROLE_JOB_ORDER,
            ],
        ];

        foreach ($employees as $employee) {
            User::updateOrCreate(
                ['email' => $employee['email']],
                array_merge($employee, [
                    'password'            => Hash::make('password123'),
                    'must_change_password' => true,
                    'email_verified_at'   => Carbon::now(),
                ])
            );
        }

        $this->command->info('55 employee users seeded successfully.');
        $this->command->info('  • 24 REGULAR  (IDs: 1,2,3,5,6,7,8,9,13,14,15,16,18,19,24,28,37,40,41,42,53,58,63,67)');
        $this->command->info('  • 31 JOB ORDER (IDs: 4,10,11,12,17,27,30,39,44,45,47,48,49,50,51,52,54,55,56,57,60,61,62,64,65,66,68,69,94,95,96)');
        $this->command->info('  • All: status=active, verification_status=verified, password=password123');
    }
}
